version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: force bundler version
          command: gem install bundler:2.2.20
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
